import libs = libboost-ext-ut%lib{ut}

./: exe{unit-tests}: ut/{hxx ixx txx cxx}{** -win_compat_test.cpp} $libs
exe{win-compat-tests}: ut/{cxx}{win_compat_test.cpp} $libs
./: exe{win-compat-tests}: include = ($cxx.target.class == 'windows')
./: exe{functional-tests}: ft/{hxx ixx txx cxx}{**} $libs

# Build options.
#
cxx.poptions =+ "-I$src_base/ft/include"
