import libs = libboost-ext-ut%lib{ut}

# For msvc, see: https://github.com/boost-ext/ut/issues/548
./: exe{unit-tests}
./: exe{functional-tests}

exe{unit-tests}: ut/{hxx ixx txx cxx}{**} $libs
exe{functional-tests}: ft/{hxx ixx txx cxx}{**} $libs

# Build options.
#
cxx.poptions =+ "-I$src_base/ft/include"
