intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{ut}: {hxx ixx txx cxx}{**} $impl_libs $intf_libs

# Build options.
#
cxx.poptions =+ "-I$out_base" "-I$src_base"

# Export options.
#
lib{ut}:
{
  cxx.export.poptions = "-I$out_base" "-I$src_base" -DBOOST_UT_DISABLE_MODULE
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{ut}: bin.lib.version = "-$version.project_id"
else
  lib{ut}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libboost-ext-ut/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
boost/{hxx ixx txx}{*}:
{
  install         = include/boost-ext/boost/
  install.subdirs = true
}
# Adjust pkg-config
cxx.pkgconfig.include = include/boost-ext/
