intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.
#import xxxx_libs += libhello%lib{hello}

lib{boost-ext-ut}: hxx{**} $impl_libs $intf_libs
lib{boost-ext-ut}: mxx{**}: include = ($cxx.features.modules == true)

modules_poption = ($cxx.features.modules ? -DBOOST_UT_ENABLE_MODULE : )

# Build options.
#
cxx.poptions =+ "-I$out_base" "-I$src_base" $modules_poption

# Export options.
#
lib{boost-ext-ut}:
{
  cxx.export.poptions = "-I$out_base" "-I$src_base" $modules_poption
  cxx.export.libs = $intf_libs
}

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{boost-ext-ut}: bin.lib.version = "-$version.project_id"
else
  lib{boost-ext-ut}: bin.lib.version = "-$version.major.$version.minor"

# Install into the libboost-ext-ut/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
boost/{hxx mxx}{*}:
{
  install         = include/boost-ext/boost/
  install.subdirs = true
}
# Adjust pkg-config
cxx.pkgconfig.include = include/boost-ext/
